"""4_private_rooms

Revision ID: 12344c8771c5
Revises: 54b57dac3cad
Create Date: 2023-02-09 12:22:18.973902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12344c8771c5'
down_revision = '54b57dac3cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'is_public')
    # ### end Alembic commands ###
