"""5_add_direct_channel_table

Revision ID: 1d2a48a48712
Revises: 12344c8771c5
Create Date: 2023-02-14 14:22:38.367725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d2a48a48712'
down_revision = '12344c8771c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_channel_user_association_table',
    sa.Column('direct_channel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['direct_channel_id'], ['direct_channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('recording', sa.Column('direct_channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recording', 'direct_channel', ['direct_channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recording', type_='foreignkey')
    op.drop_column('recording', 'direct_channel_id')
    op.drop_table('direct_channel_user_association_table')
    op.drop_table('direct_channel')
    # ### end Alembic commands ###
