"""2_user_recording_relations

Revision ID: 537201955bde
Revises: 52a5bff579bc
Create Date: 2023-02-08 10:32:30.225384

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '537201955bde'
down_revision = '52a5bff579bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('user_email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.create_foreign_key(None, 'recording', 'user', ['user_email'], ['email'], ondelete='SET NULL')
    op.add_column('transcription', sa.Column('recording_id', sa.Integer(), nullable=True))
    op.drop_constraint('transcription_room_name_fkey', 'transcription', type_='foreignkey')
    op.create_foreign_key(None, 'transcription', 'recording', ['recording_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transcription', 'room_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('room_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcription', type_='foreignkey')
    op.create_foreign_key('transcription_room_name_fkey', 'transcription', 'room', ['room_name'], ['name'], ondelete='CASCADE')
    op.drop_column('transcription', 'recording_id')
    op.drop_constraint(None, 'recording', type_='foreignkey')
    op.drop_column('recording', 'user_email')
    # ### end Alembic commands ###
