"""3_transcription_language

Revision ID: 54b57dac3cad
Revises: 537201955bde
Create Date: 2023-02-09 08:03:02.604640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b57dac3cad'
down_revision = '537201955bde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('language', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription', 'language')
    # ### end Alembic commands ###
